# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 19:43
from __future__ import unicode_literals

import collection.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIllustration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collection.models.get_image_path_illustration)),
                ('illustration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_illustration', to='collection.Illustration')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collection.models.get_image_path_pattern)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_pattern', to='collection.Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='UploadSketchbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collection.models.get_image_path_sketchbook)),
                ('sketchbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_sketchbook', to='collection.Sketchbook')),
            ],
        ),
    ]
